# Generated by Django 2.1 on 2018-08-13 16:44

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(default='Default Chat Group Name', max_length=255),
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='admin',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='allowed_users',
            field=models.ManyToManyField(related_name='users', to='chat.CustomUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.CustomUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.CustomUser'),
        ),
    ]
