# Generated by Django 2.1 on 2018-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180813_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='allowed_users',
            field=models.ManyToManyField(related_name='chat_groups', to='chat.CustomUser'),
        ),
    ]
