# Generated by Django 2.1 on 2018-08-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180810_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(default='Default Chat Group Name', max_length=255),
        ),
    ]
