# Generated by Django 2.1 on 2018-08-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_auto_20180818_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.TimeStampModel')),
                ('description', models.CharField(max_length=255)),
                ('event_type', models.SmallIntegerField(choices=[(1, 'Water Filters'), (2, 'Empty Cesspool'), (3, 'Other')])),
                ('color', models.CharField(max_length=10)),
            ],
            bases=('chat.timestampmodel',),
        ),
    ]
