# Generated by Django 2.1 on 2018-08-20 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('house_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='date_of_event',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 17, 8, 3, 351769, tzinfo=utc)),
        ),
    ]
