# Generated by Django 2.1 on 2018-08-20 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_manager', '0002_scheduledevent_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledevent',
            name='date_of_event',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 17, 9, 2, 483249)),
        ),
    ]
